# Generated by Django 2.2.5 on 2020-01-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200106_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eamil_secret',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
