# Generated by Django 2.2.5 on 2019-10-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='chekc_out',
            new_name='check_out',
        ),
    ]
